# Generated by Django 5.0.7 on 2024-08-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_writer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voicerecording',
            old_name='audio_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='voicetranscription',
            old_name='transcription_file',
            new_name='file',
        ),
    ]
