# Generated by Django 5.0.7 on 2024-08-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_writer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicetranscription',
            name='file',
        ),
        migrations.AddField(
            model_name='voicetranscription',
            name='srt_subtitles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
