# Generated by Django 5.0.7 on 2024-08-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_writer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicerecording',
            name='file',
            field=models.FileField(upload_to='user_uploads/voice'),
        ),
    ]
