# Generated by Django 5.0.7 on 2024-08-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_writer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicerecording',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
