# Generated by Django 5.0.7 on 2024-08-20 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_writer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicerecording',
            name='bitrate_kbps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='duration_ms',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='format',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='segment_count',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
