# Generated by Django 5.0.7 on 2024-08-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_writer', '0002_rename_audio_file_voicerecording_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicerecording',
            name='file',
            field=models.FileField(blank=True, upload_to='unprocessed/voice_recordings'),
        ),
        migrations.AlterField(
            model_name='voicetranscription',
            name='file',
            field=models.FileField(blank=True, upload_to='unprocessed/voice_transcriptions'),
        ),
    ]
