# Generated by Django 5.0.7 on 2024-08-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_writer', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicerecording',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
