# Generated by Django 5.0.7 on 2024-11-09 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_writer', '0003_alter_manuscript_genre_alter_manuscript_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicerecording',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='voice_writer.voicerecordingcollection'),
        ),
    ]
