# Generated by Django 5.0.7 on 2024-08-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_writer', '0003_alter_voicerecording_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicerecording',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
