# Generated by Django 5.0.7 on 2024-08-10 14:56

import voice_writer.models.voice
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_writer', '0004_voicerecording_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicerecording',
            name='file',
            field=models.FileField(blank=True, storage=voice_writer.models.voice.VoiceRecordingStorage(), upload_to='unprocessed/voice_recordings'),
        ),
    ]
