# Generated by Django 5.0.7 on 2024-08-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_writer', '0005_alter_voicerecording_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicetranscription',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
