# Generated by Django 5.0.7 on 2024-11-09 16:11

import voice_writer.models.voice
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_writer', '0005_voicesegment_cover_voicesegment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicerecording',
            name='cover',
            field=models.FileField(blank=True, max_length=255, upload_to=voice_writer.models.voice.recording_audio_upload_path),
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='file',
            field=models.FileField(max_length=255, upload_to=voice_writer.models.voice.recording_audio_upload_path),
        ),
        migrations.AlterField(
            model_name='voicerecordingcollection',
            name='cover',
            field=models.FileField(blank=True, max_length=255, upload_to=voice_writer.models.voice.collection_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='voicesegment',
            name='cover',
            field=models.FileField(blank=True, max_length=255, upload_to=voice_writer.models.voice.segment_audio_upload_path),
        ),
        migrations.AlterField(
            model_name='voicesegment',
            name='file',
            field=models.FileField(max_length=255, upload_to=voice_writer.models.voice.segment_audio_upload_path),
        ),
    ]
