# Generated by Django 5.0.7 on 2024-11-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_writer', '0006_alter_voicerecording_cover_alter_voicerecording_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicerecording',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='voicerecordingcollection',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='voicesegment',
            name='slug',
        ),
    ]
