# Generated by Django 5.0.7 on 2024-08-12 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_writer', '0006_voicetranscription_transcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicerecording',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='voicetranscription',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='voice_writer.voicerecording'),
        ),
    ]
