# Generated by Django 5.0.7 on 2024-08-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_writer', '0007_alter_voicerecording_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicerecording',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicetranscription',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
