# Generated by Django 5.0.7 on 2024-11-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_writer', '0008_alter_voicerecording_audio_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicerecording',
            name='recorded_at',
        ),
    ]
