services:
  db:
    image: postgres:16.4
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db

  celery:
    build: .
    command: celery -A voice_writer worker --loglevel=INFO
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "4"     # Set CPU limit
          memory: "4G"  # Set Memory limit
        reservations:
          cpus: "2"     # Reserve CPU
          memory: "2G"  # Reserve Memory

volumes:
  postgres_data:
