# Base stage: Install dependencies
FROM python:3.12-alpine AS base

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install system dependencies in one layer
RUN apk add --no-cache --virtual .build-deps \
    gcc \
    musl-dev \
    libffi-dev \
    openssl-dev \
    && apk add --no-cache \
    postgresql-dev \
    python3-dev \
    libpq

# Set the working directory
WORKDIR /app

# Install Python dependencies
COPY requirements.txt /app/
RUN python -m pip install --upgrade pip setuptools wheel \
    && pip install --no-cache-dir --default-timeout=10000 -r requirements.txt

# Final stage: Build the web and celery services
FROM python:3.12-alpine

# Copy installed dependencies from the base stage
COPY --from=base /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=base /usr/local/bin /usr/local/bin

# Set the working directory
WORKDIR /app

# Copy the application code
COPY . /app/

CMD ["sh", "-c", "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --reload"]