services:
  - type: web
    name: voice-writer-web
    runtime: docker
    repo: https://github.com/thoughtpunch/voice-writer.git
    branch: main
    plan: starter
    dockerCommand: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    domains:
      - voicewriter.app
      - voicewriter.pro
    envVars:
      - fromGroup: voice-writer-env-group
      - key: DATABASE_URL
        fromDatabase:
          name: voice-writer-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: voice-writer-redis
          property: connectionString

  - type: worker
    name: voice-writer-celery
    runtime: docker
    repo: https://github.com/thoughtpunch/voice-writer.git
    branch: main
    plan: starter
    dockerCommand: celery -A voice_writer worker --loglevel=INFO
    envVars:
      - fromGroup: voice-writer-env-group
      - key: DATABASE_URL
        fromDatabase:
          name: voice-writer-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: voice-writer-redis
          property: connectionString

  - type: redis
    name: voice-writer-redis
    plan: free
    ipAllowList: [] # No entries in the IP allow list

databases:
  - name: voice-writer-db
    databaseName: voice_writer
    user: voice_writer
    plan: free
    region: oregon
    ipAllowList: [] # No entries in the IP allow list
    postgresMajorVersion: "16"

envVarGroups:
  - name: voice-writer-env-group
    envVars:
      - key: DEBUG
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        value: "voice-writer-dev"
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ENDPOINT_URL
        sync: false
      - key: R2_REGION_NAME
        value: "us-east-1"